language: ruby
rvm:
 - 1.9.3
 - 2.0.0

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres

before_script: 
  - "psql -c 'create database myapp_test;' -U postgres"
  - "rake db:migrate"


